apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusteragents.appdynamics.com
spec:
  group: appdynamics.com
  names:
    kind: Clusteragent
    listKind: ClusteragentList
    plural: clusteragents
    singular: clusteragent
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            account:
              type: string
            agentEnvVar:
              type: string
            agentLabel:
              type: string
            agentMountName:
              type: string
            agentMountPath:
              type: string
            agentSSLCert:
              type: string
            agentServerPort:
              format: int32
              type: integer
            analyticsAgentContainerName:
              type: string
            analyticsAgentImage:
              type: string
            analyticsAgentUrl:
              type: string
            appDAnalyticsLabel:
              type: string
            appDAppLabel:
              type: string
            appDDotNetAttachImage:
              type: string
            appDInitContainerName:
              type: string
            appDJavaAttachImage:
              type: string
            appDTierLabel:
              type: string
            appLogMountName:
              type: string
            appLogMountPath:
              type: string
            appName:
              type: string
            args:
              items:
                type: string
              type: array
            biqRequestCpu:
              type: string
            biqRequestMem:
              type: string
            biqService:
              type: string
            containerSchemaName:
              type: string
            controllerUrl:
              description: account info
              type: string
            daemonSchemaName:
              type: string
            dashboardDelayMin:
              format: int64
              type: integer
            dashboardSuffix:
              description: dashboard
              type: string
            dashboardTemplatePath:
              type: string
            defaultInstrumentationTech:
              type: string
            deploySchemaName:
              type: string
            env:
              items:
                type: object
              type: array
            epSchemaName:
              type: string
            eventAPILimit:
              description: limits
              format: int64
              type: integer
            eventSchemaName:
              type: string
            eventServiceUrl:
              type: string
            globalAccount:
              type: string
            image:
              type: string
            initContainerDir:
              type: string
            initRequestCpu:
              type: string
            initRequestMem:
              type: string
            instrumentContainer:
              type: string
            instrumentMatchString:
              items:
                type: string
              type: array
            instrumentRule:
              items:
                properties:
                  appDAppLabel:
                    type: string
                  appDTierLabel:
                    type: string
                  biQ:
                    type: string
                  containerName:
                    type: string
                  matchString:
                    items:
                      type: string
                    type: array
                  method:
                    description: string matched against deployment names and labels,
                      supports regex
                    type: string
                  namespaces:
                    items:
                      type: string
                    type: array
                  tech:
                    type: string
                  version:
                    type: string
                type: object
              type: array
            instrumentationMethod:
              description: instrumentation
              type: string
            jDKMountName:
              type: string
            jDKMountPath:
              type: string
            jobSchemaName:
              type: string
            logLevel:
              type: string
            logLines:
              format: int64
              type: integer
            logSchemaName:
              type: string
            metricsSyncInterval:
              format: int64
              type: integer
            nodeNamePrefix:
              type: string
            nodeSchemaName:
              type: string
            nodesToMonitor:
              items:
                type: string
              type: array
            nodesToMonitorExclude:
              items:
                type: string
              type: array
            nsSchemaName:
              type: string
            nsToInstrument:
              items:
                type: string
              type: array
            nsToInstrumentExclude:
              items:
                type: string
              type: array
            nsToMonitor:
              items:
                type: string
              type: array
            nsToMonitorExclude:
              items:
                type: string
              type: array
            overconsumptionThreshold:
              format: int64
              type: integer
            podEventNumber:
              format: int64
              type: integer
            podSchemaName:
              description: snapshot schemas
              type: string
            proxyPass:
              type: string
            proxyUrl:
              type: string
            proxyUser:
              type: string
            rSSchemaName:
              type: string
            resources:
              type: object
            rqSchemaName:
              type: string
            snapshotSyncInterval:
              format: int64
              type: integer
            systemSSLCert:
              type: string
          required:
          - controllerUrl
          type: object
        status:
          properties:
            lastUpdateTime:
              description: 'Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file'
              format: date-time
              type: string
            state:
              properties:
                analyticsAgentImage:
                  type: string
                appDDotNetAttachImage:
                  type: string
                appDJavaAttachImage:
                  type: string
                biqService:
                  type: string
                defaultInstrumentationTech:
                  type: string
                instrumentMatchString:
                  items:
                    type: string
                  type: array
                instrumentRule:
                  items:
                    properties:
                      appDAppLabel:
                        type: string
                      appDTierLabel:
                        type: string
                      biQ:
                        type: string
                      containerName:
                        type: string
                      matchString:
                        items:
                          type: string
                        type: array
                      method:
                        description: string matched against deployment names and labels,
                          supports regex
                        type: string
                      namespaces:
                        items:
                          type: string
                        type: array
                      tech:
                        type: string
                      version:
                        type: string
                    type: object
                  type: array
                instrumentationMethod:
                  type: string
                logLevel:
                  type: string
                logLines:
                  format: int64
                  type: integer
                metricsSyncInterval:
                  format: int64
                  type: integer
                nodesToMonitor:
                  items:
                    type: string
                  type: array
                nodesToMonitorExclude:
                  items:
                    type: string
                  type: array
                nsToInstrument:
                  items:
                    type: string
                  type: array
                nsToInstrumentExclude:
                  items:
                    type: string
                  type: array
                nsToMonitor:
                  items:
                    type: string
                  type: array
                nsToMonitorExclude:
                  items:
                    type: string
                  type: array
                snapshotSyncInterval:
                  format: int64
                  type: integer
                version:
                  type: string
              required:
              - metricsSyncInterval
              - snapshotSyncInterval
              - logLevel
              - logLines
              type: object
          required:
          - lastUpdateTime
          - state
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
