apiVersion: appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  controllerUrl: "http://appdynamics.com"
  image: "docker.io/appdynamics/cluster-agent:latest"
  appName: "GKEAgent"
  instrumentationMethod: "mountEnv"
  instrumentMatchString:  # full match or regex of the deployment names that you want to instrument.
  - api
  nsToInstrument:  # namespace to instrument
  - ns1
  biqService: "proxy"
  appDAppLabel: "platform" 
---
apiVersion: appdynamics.com/v1alpha1
kind: InfraViz
metadata:
  name: appd-infraviz
  namespace: appdynamics
spec:
  controllerUrl: "http://appdynamics.com"
  image: "docker.io/appdynamics/machine-agent-analytics:latest"
  account: "<appd-account-name>"
  globalAccount: "<appd-global-account-name"
 
 
  