apiVersion: appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  controllerUrl: "http://4511controllernoss-auto-dp0309se.srv.ravcloud.com:8090"
  image: "docker.io/appdynamics/cluster-agent:0.3.0"
  logLevel: "info"
  appName: "OpenShiftAgent"
  instrumentationMethod: "none"
  appNameLiteral: "Sabre"
  netVizPort: 3892
  instrumentRule:
  - namespaces:
    - dev
    method: mountEnv
    matchString:
    - ai
    - world
    - loan
    - player
    - api
 
  