apiVersion: appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  controllerUrl: "http://appdynamics.com"
  image: "docker.io/appdynamics/cluster-agent:latest"
  logLevel: "info"
  instrumentationMethod: "mountEnv"
  instrumentMatchString:  # full match or regex of the deployment names that you want to instrument.
  - client-api
  nsToInstrument:  # namespace to instrument
  - dev
  appDAppLabel: "platform"
 
  