apiVersion: appdynamics.com/v1alpha1
kind: InfraViz
metadata:
  name: appd-infraviz
  namespace: appdynamics
spec:
  controllerUrl: "<http:\\acme.saas.appdynamics.com"
  image: "docker.io/appdynamics/machine-agent-analytics:latest"
  account: "<account-name>"
  globalAccount: "<global-account-name>"
  enableMasters: true
  stdoutLogging: true
